site_name: GHGA Developer Cookbook

theme:
  name: material
  favicon: ./imgs/favicon.png
  logo: ./imgs/favicon.png
  palette:
    scheme: default
    primary: blue grey
  features:
    - navigation.tabs
